# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "title:dsc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "SubName", name: "subname", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - label: "Sections"
        name: "sections"
        widget: "object"
        collapsed: true
        fields:
        - {label: "Section", name: "section", widget: "markdown", required: false}
        - {label: "Section", name: "section", widget: "markdown", required: false}
        - {label: "Section", name: "section", widget: "markdown", required: false}
        - {label: "Section", name: "section", widget: "markdown", required: false}
        - label: "Clients"
          name: "clients"
          widget: "object"
          collapsed: true
          fields:
          - {label: "Client", name: "client", widget: "image", required: false}
      - {label: "Working", name: "working", widget: "string", tagname: "h3"}
      - {label: "Teaching", name: "teaching", widget: "markdown", tagname: "h3"}
      - {label: "Awards", name: "awards", widget: "markdown", tagname: "h3"}
      - {label: "Website", name: "website", widget: "string", tagname: "h3"}
      - {label: "Instagram", name: "imstagram", widget: "string", tagname: "h3"}
      - {label: "Footer", name: "footer", widget: "markdown", tagname: "h2"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
